# -- Markup --
# These settings are required for the theme to function.

[goldmark]
[goldmark.renderer]
  unsafe = true

[highlight]
  noClasses = true #If set to true, it will use default congo colours
  style = "monokai"
  lineNos = false

[tableOfContents]
  startLevel = 2
  endLevel = 4
