baseurl = "/"
languageCode = 'en-us'
title = 'Papafe'
theme='archie'
enableEmoji = true

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/papafe"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/papafeit"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4